# Generated by Django 3.0.3 on 2020-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
